### ISSUE TITLE
Le module ne s'affiche pas

### ISSUE THREAD

**Issue by twister25000** [TexGG/MMM-Ginko#1]
Salut ! Je suis bisontin et j'aurais aimé intégré ton super module à mon Magic Mirror mais malheureusement il ne s'affiche pas. Au lancement je n'ai aucun message d'erreur.
Peux tu m'aider stp

Merci

**Comment by TexGG** [comment]
Hello,

Pourrais-tu me transmettre ta config stp ? Comme point de départ de debug :)

**Comment by twister25000** [comment]
J'ai suivi ton exemple de configuration dans un premier temps
![config](https://cloud.githubusercontent.com/assets/28902296/26467272/34c4771e-4192-11e7-83cb-76b931590eeb.PNG)

J'ai bien suivi le process d'installation et après j'ai eu ceci
![conf2](https://cloud.githubusercontent.com/assets/28902296/26467307/5beb72c0-4192-11e7-9813-b413723c4518.PNG)

**Comment by TexGG** [comment]
C'est peut-être parce que je suis idiot et que j'ai pas corrigé l'exemple après avoir "anglifié" mon code ...

Je corrige et je fait un commit, il suffira d'appliquer le nouvel exemple. J'en profite pour corriger le warning sur la licence, merci pour cette remontée :)

**Comment by twister25000** [comment]
No problème. Merci à toi
J'aimerais te poser une autre question peux tu me dire où as tu trouvé ton miroir sans tain ? J'en cherche mais c'est vraiment hors de prix.

Merci

**Comment by TexGG** [comment]
Voilà exemple corrigé, et faire un petit "git pull" pour corriger la licence. Tiens moi au courant si ça fonctionne mieux.

Je n'ai pas de "vrai" mirroir sans tain, car comme tu le dis c'est hors de prix. J'ai opté pour la solution "cheap" : plaque de plexiglass avec film miroir pour vitre. La plaque de plexi coute 10€ pour 50cmx50cm (nickel pour 22") et 20€ pour du 50cmx100cm (pour > 22"), et le film miroir coute dans les 15€, ce qui te fait un tout à 25€ pour un "miroir" de 22". 
Le résultat vaut pas un vrai miroir sans tain, mais si tu as une bonne luminositer, ça le fait. Par contre je te conseille de prendre un film "repositionnable" parce que c'est pas simple de le mettre sans se foirer ...

**Comment by twister25000** [comment]
J'aurais bien aimé te dire que ça fonctionne mais ce n'est pas le cas.
Je ne sais pas si c'est un oublie ou pas mais j'ai noté qu'il manquait une virgule à la fin de cette ligne : 
directions: ["0","0","0","1","1"]

Mais avec ou sans je n'ai malheureusement rien qui s'affiche

**Comment by TexGG** [comment]
Hum là par contre je ne vois pas car j'ai refait le processus d'install à la virgule près (non obligatoire après le dernier argument de "config"), et tout fonctionne. Il peut y avoir un problème avec l'encodage des "ç", il faudrait essayer avec cette config pour en être sûr:
`
 config: {
        stations: ["Gare Viotte"],
        lines: ["102"],
        directions: ["0"]
    }
`

et sinon, tu peux lancer arrêter ton miroir ("p2m stop mm" ?), aller dans le dossier "MagicMirror" et le relancer avec `DISPLAY=:0 npm start`, et observer les traces et erreurs.

**Comment by twister25000** [comment]
J'arrive à lancer le miroir avec la commande npm start et pour quitter l'interface du miroir je fais ctrl+ Q

En essayant avec la config que tu m'as donné je n'ai tjs rien d'affiché.

J'ai peut être mal mis à jour les modifications, j'ai juste copier les fichier modifiés. Y a t il une manip pour mettre à jour ?

Peux tu aussi m'expliquer quand tu me dit de relancer avec DISPLAY=0 je ne vois pas comment ni où faire ça


Merci


________________________________
De : Gervais Gwenaël <notifications@github.com>
Envoyé : vendredi 26 mai 2017 08:02
À : TexGG/MMM-Ginko
Cc : twister25000; Author
Objet : Re: [TexGG/MMM-Ginko] Le module ne s'affiche pas (#1)


Hum là par contre je ne vois pas car j'ai refait le processus d'install à la virgule près (non obligatoire après le dernier argument de "config"), et tout fonctionne. Il peut y avoir un problème avec l'encodage des "ç", il faudrait essayer avec cette config pour en être sûr:
config: { stations: ["Gare Viotte"], lines: ["102"], directions: ["0"] }

et sinon, tu peux lancer arrêter ton miroir ("p2m stop mm" ?), aller dans le dossier "MagicMirror" et le relancer avec DISPLAY=:0 npm start, et observer les traces et erreurs.

**Comment by TexGG** [comment]
Les fichiers que j'ai modifiés n'ont pas d'importance sur le problème que tu avais, seul l'exemple présent dans le Readme en avait.
J'utilise la commande "git clone" pour récupérer les modules et "git pull" pour les mettre à jour, mais si tu as passé par le téléchargement de l'archive et l'upload des fichiers "à la main", il faut refaire pareil.

Ce que j'indique de faire c'est de lancer la commande "DISPLAY=:0 npm start" dans une console linux (directement sur le miroir, ou en SSH. Cela affichera les traces/logs dans la console et permettra de repérer les erreurs.

**Comment by twister25000** [comment]
Merci pour ton aide voici le résultat de la commande


[cid:b4465ccf-2b5d-4e07-a3d8-c28ca71ce5e9]


________________________________
De : Gervais Gwenaël <notifications@github.com>
Envoyé : vendredi 26 mai 2017 15:43
À : TexGG/MMM-Ginko
Cc : twister25000; Author
Objet : Re: [TexGG/MMM-Ginko] Le module ne s'affiche pas (#1)


Les fichiers que j'ai modifiés n'ont pas d'importance sur le problème que tu avais, seul l'exemple présent dans le Readme en avait.
J'utilise la commande "git clone" pour récupérer les modules et "git pull" pour les mettre à jour, mais si tu as passé par le téléchargement de l'archive et l'upload des fichiers "à la main", il faut refaire pareil.

Ce que j'indique de faire c'est de lancer la commande "DISPLAY=:0 npm start" dans une console linux (directement sur le miroir, ou en SSH. Cela affichera les traces/logs dans la console et permettra de repérer les erreurs.

**Comment by twister25000** [comment]
Je pense savoir pourquoi ça ne fonctionne pas.

Dans ton module tu précises qu'en terme de dépendance il faut request. Je pense que je ne l'ai pas installé. Peux tu me donner des détails sur cette dépendance merci


________________________________
De : Gervais Gwenaël <notifications@github.com>
Envoyé : vendredi 26 mai 2017 15:43
À : TexGG/MMM-Ginko
Cc : twister25000; Author
Objet : Re: [TexGG/MMM-Ginko] Le module ne s'affiche pas (#1)


Les fichiers que j'ai modifiés n'ont pas d'importance sur le problème que tu avais, seul l'exemple présent dans le Readme en avait.
J'utilise la commande "git clone" pour récupérer les modules et "git pull" pour les mettre à jour, mais si tu as passé par le téléchargement de l'archive et l'upload des fichiers "à la main", il faut refaire pareil.

Ce que j'indique de faire c'est de lancer la commande "DISPLAY=:0 npm start" dans une console linux (directement sur le miroir, ou en SSH. Cela affichera les traces/logs dans la console et permettra de repérer les erreurs.

**Comment by TexGG** [comment]
Je ne vois pas le résultat :
> Merci pour ton aide voici le résultat de la commande
>[cid:b4465ccf-2b5d-4e07-a3d8-c28ca71ce5e9]

Normalement "request" s'installe tout seul via le npm install qui se base sur le [package.json](https://github.com/TexGG/MMM-Ginko/blob/master/package.json), il n'y donc pas à s'en préoccuper.

**Comment by twister25000** [comment]
Excuse moi il n'a pas pris mon fichier. Je te l'ai mis en PJ

Je ne vois pas d'erreur ni de ligne correspondant au module Ginko. J'ai d'ailleurs eu le même cas pour deux autres modules que j'avais installé et paramétré. MM se lance mais n'affiche pas les modules. J'avais installé volumio, et un module qui affiche la qualité de l'air

________________________________
De : Gervais Gwenaël <notifications@github.com>
Envoyé : vendredi 26 mai 2017 16:38
À : TexGG/MMM-Ginko
Cc : twister25000; Author
Objet : Re: [TexGG/MMM-Ginko] Le module ne s'affiche pas (#1)


Je ne vois pas le résultat :

Merci pour ton aide voici le résultat de la commande
[cid:b4465ccf-2b5d-4e07-a3d8-c28ca71ce5e9]

Normalement "request" s'installe tout seul via le npm install qui se base sur le package.json<https://github.com/TexGG/MMM-Ginko/blob/master/package.json>, il n'y donc pas à s'en préoccuper.

**Comment by TexGG** [comment]
Dans ce cas là, on dirait plutôt que tu ne met pas les dossiers de module au bon endroit, ou que les paramètres de configuration ne sont pas pris en compte.

Voici en gros ma hiérarchie de fichiers pour le module, et pour le fichier de config si ça peut aider:
```
MagicMirror/
├── modules/
│   ├── MMM-Ginko/
│   │   ├── LICENSE
│   │   ├── MMM-Ginko.css
│   │   ├── MMM-Ginko.js
│   │   ├── node_helper.js
│   │   ├── node_modules/
│   │   ├── package.json
│   │   ├── README.md
│   │   ├── translations/
│   ├── MMM-Ginko/
├── config/
│   └── config.js
```

sinon tu devrait avoir des lignes comme celles-là :
```

pi@mirrorpi:~/MagicMirror $ DISPLAY=:0 npm start

> magicmirror@2.1.1 start /home/pi/MagicMirror
> sh run-start.sh

Starting MagicMirror: v2.1.1
Loading config ...
Loading module helpers ...
No helper found for module: alert.
Initializing new module helper ...
Module helper loaded: updatenotification
Initializing new module helper ...
Module helper loaded: MMM-ModuleScheduler
No helper found for module: clock.
Initializing new module helper ...
Module helper loaded: updatenotification
Initializing new module helper ...
Module helper loaded: MMM-ModuleScheduler
No helper found for module: clock.
Initializing new module helper ...
Module helper loaded: calendar
No helper found for module: compliments.
No helper found for module: currentweather.
No helper found for module: weatherforecast.
Initializing new module helper ...
Module helper loaded: newsfeed
Initializing new module helper ...
Module helper loaded: MMM-Ginko
Initializing new module helper ...
Module helper loaded: MMM-FreeBox-Monitor
No helper found for module: airquality.
All module helpers loaded.
Starting server on port 8080 ...
Starting server op port 8080 ...
Server started ...
Connecting socket for: updatenotification
Connecting socket for: MMM-ModuleScheduler
Starting node helper for: MMM-ModuleScheduler
Connecting socket for: calendar
Starting node helper for: calendar
Connecting socket for: newsfeed
Starting module: newsfeed
Connecting socket for: MMM-Ginko
Starting node helper for: MMM-Ginko
Connecting socket for: MMM-FreeBox-Monitor
Starting module: MMM-FreeBox-Monitor
Sockets connected & modules started ...
Launching application.
.......

```

**Comment by twister25000** [comment]
ça y est je viens de comprendre mon problème en lisant ta réponse. Effectivement je ne mettais pas le module au bon endroit. Je mettais le module dans /home/pi/MagicMirror/module/default

J'ai remonté le répertoire du module Ginko dans module et tout fonctionne très bien. Je te remercie pour ton aide


________________________________
De : Gervais Gwenaël <notifications@github.com>
Envoyé : vendredi 26 mai 2017 18:03
À : TexGG/MMM-Ginko
Cc : twister25000; Author
Objet : Re: [TexGG/MMM-Ginko] Le module ne s'affiche pas (#1)


Dans ce cas là, on dirait plutôt que tu ne met pas les dossiers de module au bon endroit, ou que les paramètres de configuration ne sont pas pris en compte.

Voici en gros ma hiérarchie de fichiers pour le module, et pour le fichier de config si ça peut aider:

MagicMirror/
├── modules/
│   ├── MMM-Ginko/
│   │   ├── LICENSE
│   │   ├── MMM-Ginko.css
│   │   ├── MMM-Ginko.js
│   │   ├── node_helper.js
│   │   ├── node_modules/
│   │   ├── package.json
│   │   ├── README.md
│   │   ├── translations/
│   ├── MMM-Ginko/
├── config/
│   └── config.js


sinon tu devrait avoir des lignes comme celles-là :


pi@mirrorpi:~/MagicMirror $ DISPLAY=:0 npm start

> magicmirror@2.1.1 start /home/pi/MagicMirror
> sh run-start.sh

Starting MagicMirror: v2.1.1
Loading config ...
Loading module helpers ...
No helper found for module: alert.
Initializing new module helper ...
Module helper loaded: updatenotification
Initializing new module helper ...
Module helper loaded: MMM-ModuleScheduler
No helper found for module: clock.
Initializing new module helper ...
Module helper loaded: updatenotification
Initializing new module helper ...
Module helper loaded: MMM-ModuleScheduler
No helper found for module: clock.
Initializing new module helper ...
Module helper loaded: calendar
No helper found for module: compliments.
No helper found for module: currentweather.
No helper found for module: weatherforecast.
Initializing new module helper ...
Module helper loaded: newsfeed
Initializing new module helper ...
Module helper loaded: MMM-Ginko
Initializing new module helper ...
Module helper loaded: MMM-FreeBox-Monitor
No helper found for module: airquality.
All module helpers loaded.
Starting server on port 8080 ...
Starting server op port 8080 ...
Server started ...
Connecting socket for: updatenotification
Connecting socket for: MMM-ModuleScheduler
Starting node helper for: MMM-ModuleScheduler
Connecting socket for: calendar
Starting node helper for: calendar
Connecting socket for: newsfeed
Starting module: newsfeed
Connecting socket for: MMM-Ginko
Starting node helper for: MMM-Ginko
Connecting socket for: MMM-FreeBox-Monitor
Starting module: MMM-FreeBox-Monitor
Sockets connected & modules started ...
Launching application.
.......

**Comment by TexGG** [comment]
Content d'avoir pu aider, et corriger au passage quelques petites erreurs.
